---
apiVersion: v1
kind: Namespace
metadata:
  name: system-argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm/
  chart: argo-cd
  targetNamespace: system-argocd
  valuesContent: |-
    config:
      params:
        server.insecure: true
    redis-ha:
      enabled: false
    controller:
      replicas: 1
    server:
      replicas: 1
      ingress:
        enabled: false
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.152
    repoServer:
      replicas: 1
    applicationSet:
      replicas: 1