---
apiVersion: v1
kind: Namespace
metadata:
  name: system-nfs-provisioner
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  chart: nfs-subdir-external-provisioner
  targetNamespace: system-nfs-provisioner
  valuesContent: |-
    storageClass:
      defaultClass: true
    nfs:
      server: 127.0.0.1
      path: /export/kubernetes